import type { IFilm } from "../models/Film.js";

/**
 * VOCABOLARIO CONTROLLATO dei generi.
 * Regola d'oro: l'algoritmo confronta stringhe, quindi "Fantascienza" e "Sci-Fi"
 * sarebbero due generi DIVERSI e non farebbero mai match. Definire una lista
 * chiusa di valori ammessi evita silenziosamente tonnellate di bug.
 */
export const GENERI = [
  "Azione",
  "Avventura",
  "Fantascienza",
  "Thriller",
  "Dramma",
  "Commedia",
  "Horror",
  "Crime",
  "Fantasy",
  "Animazione",
  "Mistero",
  "Romantico",
  "Guerra",
  "Biografico",
] as const;

/** Catalogo di esempio: 24 titoli tra film e serie, generi ben distribuiti. */
export const catalogo: IFilm[] = [
  {
    titolo: "Inception",
    tipo: "film",
    generi: ["Fantascienza", "Azione", "Thriller"],
    tag: ["sogni", "heist", "mente", "realtà alterata"],
    anno: 2010,
    durataMinuti: 148,
    piattaforma: "Netflix",
    regista: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    descrizione: "Un ladro che ruba segreti dai sogni riceve l'incarico di impiantare un'idea.",
    posterUrl: "https://placehold.co/300x450?text=Inception",
    votoMedio: 8.8,
  },
  {
    titolo: "Interstellar",
    tipo: "film",
    generi: ["Fantascienza", "Dramma", "Avventura"],
    tag: ["spazio", "viaggi nel tempo", "padre e figlia", "buchi neri"],
    anno: 2014,
    durataMinuti: 169,
    piattaforma: "Prime Video",
    regista: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    descrizione: "Un gruppo di esploratori attraversa un wormhole per salvare l'umanità.",
    posterUrl: "https://placehold.co/300x450?text=Interstellar",
    votoMedio: 8.7,
  },
  {
    titolo: "Blade Runner 2049",
    tipo: "film",
    generi: ["Fantascienza", "Dramma", "Mistero"],
    tag: ["distopico", "androidi", "noir", "identità"],
    anno: 2017,
    durataMinuti: 164,
    piattaforma: "Netflix",
    regista: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    descrizione: "Un blade runner scopre un segreto capace di far precipitare la società.",
    posterUrl: "https://placehold.co/300x450?text=Blade+Runner+2049",
    votoMedio: 8.0,
  },
  {
    titolo: "Arrival",
    tipo: "film",
    generi: ["Fantascienza", "Dramma", "Mistero"],
    tag: ["alieni", "linguaggio", "tempo non lineare", "primo contatto"],
    anno: 2016,
    durataMinuti: 116,
    piattaforma: "Prime Video",
    regista: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    descrizione: "Una linguista tenta di comunicare con visitatori extraterrestri.",
    posterUrl: "https://placehold.co/300x450?text=Arrival",
    votoMedio: 7.9,
  },
  {
    titolo: "Dune",
    tipo: "film",
    generi: ["Fantascienza", "Avventura", "Dramma"],
    tag: ["deserto", "politica", "profezia", "spazio"],
    anno: 2021,
    durataMinuti: 155,
    piattaforma: "Netflix",
    regista: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
    descrizione: "L'erede di una nobile casata affronta il proprio destino su un pianeta ostile.",
    posterUrl: "https://placehold.co/300x450?text=Dune",
    votoMedio: 8.0,
  },
  {
    titolo: "Il Cavaliere Oscuro",
    tipo: "film",
    generi: ["Azione", "Crime", "Dramma"],
    tag: ["supereroi", "caos", "gotham", "vigilante"],
    anno: 2008,
    durataMinuti: 152,
    piattaforma: "Prime Video",
    regista: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    descrizione: "Batman affronta un criminale anarchico che vuole piegare Gotham.",
    posterUrl: "https://placehold.co/300x450?text=Il+Cavaliere+Oscuro",
    votoMedio: 9.0,
  },
  {
    titolo: "Mad Max: Fury Road",
    tipo: "film",
    generi: ["Azione", "Avventura", "Fantascienza"],
    tag: ["post-apocalittico", "inseguimento", "deserto"],
    anno: 2015,
    durataMinuti: 120,
    piattaforma: "Netflix",
    regista: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron"],
    descrizione: "Una fuga attraverso il deserto contro un tiranno e la sua armata.",
    posterUrl: "https://placehold.co/300x450?text=Fury+Road",
    votoMedio: 8.1,
  },
  {
    titolo: "Se7en",
    tipo: "film",
    generi: ["Thriller", "Crime", "Mistero"],
    tag: ["serial killer", "investigazione", "cupo", "peccati capitali"],
    anno: 1995,
    durataMinuti: 127,
    piattaforma: "Netflix",
    regista: "David Fincher",
    cast: ["Brad Pitt", "Morgan Freeman", "Kevin Spacey"],
    descrizione: "Due detective danno la caccia a un killer ispirato ai sette peccati capitali.",
    posterUrl: "https://placehold.co/300x450?text=Se7en",
    votoMedio: 8.6,
  },
  {
    titolo: "Il Silenzio degli Innocenti",
    tipo: "film",
    generi: ["Thriller", "Crime", "Horror"],
    tag: ["serial killer", "psicologico", "FBI", "profiling"],
    anno: 1991,
    durataMinuti: 118,
    piattaforma: "Prime Video",
    regista: "Jonathan Demme",
    cast: ["Jodie Foster", "Anthony Hopkins"],
    descrizione: "Una cadetta dell'FBI chiede aiuto a un killer cannibale per catturarne un altro.",
    posterUrl: "https://placehold.co/300x450?text=Silenzio+Innocenti",
    votoMedio: 8.6,
  },
  {
    titolo: "Parasite",
    tipo: "film",
    generi: ["Thriller", "Dramma", "Commedia"],
    tag: ["classi sociali", "inganno", "satira", "colpo di scena"],
    anno: 2019,
    durataMinuti: 132,
    piattaforma: "Prime Video",
    regista: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun"],
    descrizione: "Una famiglia povera si insinua nella vita di una ricca.",
    posterUrl: "https://placehold.co/300x450?text=Parasite",
    votoMedio: 8.5,
  },
  {
    titolo: "Il Padrino",
    tipo: "film",
    generi: ["Crime", "Dramma"],
    tag: ["mafia", "famiglia", "potere", "epico"],
    anno: 1972,
    durataMinuti: 175,
    piattaforma: "Netflix",
    regista: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    descrizione: "La successione al vertice di una dinastia mafiosa newyorkese.",
    posterUrl: "https://placehold.co/300x450?text=Il+Padrino",
    votoMedio: 9.2,
  },
  {
    titolo: "Whiplash",
    tipo: "film",
    generi: ["Dramma"],
    tag: ["musica", "ossessione", "mentore tossico", "jazz"],
    anno: 2014,
    durataMinuti: 106,
    piattaforma: "Netflix",
    regista: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons"],
    descrizione: "Un giovane batterista viene spinto oltre ogni limite dal suo insegnante.",
    posterUrl: "https://placehold.co/300x450?text=Whiplash",
    votoMedio: 8.5,
  },
  {
    titolo: "La La Land",
    tipo: "film",
    generi: ["Romantico", "Dramma", "Commedia"],
    tag: ["musical", "los angeles", "sogni", "jazz"],
    anno: 2016,
    durataMinuti: 128,
    piattaforma: "Disney+",
    regista: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone"],
    descrizione: "Un pianista e un'aspirante attrice tra amore e ambizione.",
    posterUrl: "https://placehold.co/300x450?text=La+La+Land",
    votoMedio: 8.0,
  },
  {
    titolo: "Notting Hill",
    tipo: "film",
    generi: ["Romantico", "Commedia"],
    tag: ["londra", "celebrità", "commedia romantica"],
    anno: 1999,
    durataMinuti: 124,
    piattaforma: "Prime Video",
    regista: "Roger Michell",
    cast: ["Julia Roberts", "Hugh Grant"],
    descrizione: "Un libraio londinese si innamora di una star del cinema.",
    posterUrl: "https://placehold.co/300x450?text=Notting+Hill",
    votoMedio: 7.2,
  },
  {
    titolo: "Shining",
    tipo: "film",
    generi: ["Horror", "Thriller", "Mistero"],
    tag: ["hotel isolato", "follia", "soprannaturale", "inverno"],
    anno: 1980,
    durataMinuti: 146,
    piattaforma: "Netflix",
    regista: "Stanley Kubrick",
    cast: ["Jack Nicholson", "Shelley Duvall"],
    descrizione: "Un uomo perde la ragione nell'hotel isolato di cui è custode.",
    posterUrl: "https://placehold.co/300x450?text=Shining",
    votoMedio: 8.4,
  },
  {
    titolo: "Hereditary",
    tipo: "film",
    generi: ["Horror", "Dramma", "Mistero"],
    tag: ["famiglia", "lutto", "occulto", "disturbante"],
    anno: 2018,
    durataMinuti: 127,
    piattaforma: "Prime Video",
    regista: "Ari Aster",
    cast: ["Toni Collette", "Alex Wolff"],
    descrizione: "Una famiglia scopre un'eredità oscura dopo la morte della nonna.",
    posterUrl: "https://placehold.co/300x450?text=Hereditary",
    votoMedio: 7.3,
  },
  {
    titolo: "Il Signore degli Anelli: La Compagnia dell'Anello",
    tipo: "film",
    generi: ["Fantasy", "Avventura", "Azione"],
    tag: ["epico", "viaggio", "magia", "amicizia"],
    anno: 2001,
    durataMinuti: 178,
    piattaforma: "Prime Video",
    regista: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    descrizione: "Una compagnia parte per distruggere un anello che corrompe chi lo possiede.",
    posterUrl: "https://placehold.co/300x450?text=LOTR",
    votoMedio: 8.9,
  },
  {
    titolo: "Spirited Away",
    tipo: "film",
    generi: ["Animazione", "Fantasy", "Avventura"],
    tag: ["mondo degli spiriti", "crescita", "giappone", "onirico"],
    anno: 2001,
    durataMinuti: 125,
    piattaforma: "Netflix",
    regista: "Hayao Miyazaki",
    cast: ["Rumi Hiiragi", "Miyu Irino"],
    descrizione: "Una bambina finisce in un mondo di spiriti e deve salvare i genitori.",
    posterUrl: "https://placehold.co/300x450?text=Spirited+Away",
    votoMedio: 8.6,
  },
  {
    titolo: "Spider-Man: Un Nuovo Universo",
    tipo: "film",
    generi: ["Animazione", "Azione", "Avventura"],
    tag: ["supereroi", "multiverso", "crescita", "stile visivo"],
    anno: 2018,
    durataMinuti: 117,
    piattaforma: "Netflix",
    regista: "Bob Persichetti",
    cast: ["Shameik Moore", "Jake Johnson"],
    descrizione: "Miles Morales incontra gli Spider-Man di altre dimensioni.",
    posterUrl: "https://placehold.co/300x450?text=Spider-Verse",
    votoMedio: 8.4,
  },
  {
    titolo: "Breaking Bad",
    tipo: "serie",
    generi: ["Crime", "Dramma", "Thriller"],
    tag: ["antieroe", "droga", "trasformazione", "new mexico"],
    anno: 2008,
    durataMinuti: 49,
    piattaforma: "Netflix",
    regista: "Vince Gilligan",
    cast: ["Bryan Cranston", "Aaron Paul"],
    descrizione: "Un professore di chimica malato diventa produttore di metanfetamina.",
    posterUrl: "https://placehold.co/300x450?text=Breaking+Bad",
    votoMedio: 9.5,
  },
  {
    titolo: "Stranger Things",
    tipo: "serie",
    generi: ["Fantascienza", "Horror", "Mistero"],
    tag: ["anni 80", "amicizia", "dimensione parallela", "nostalgia"],
    anno: 2016,
    durataMinuti: 51,
    piattaforma: "Netflix",
    regista: "Duffer Brothers",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
    descrizione: "Un gruppo di ragazzi affronta forze soprannaturali in una cittadina.",
    posterUrl: "https://placehold.co/300x450?text=Stranger+Things",
    votoMedio: 8.7,
  },
  {
    titolo: "Dark",
    tipo: "serie",
    generi: ["Fantascienza", "Mistero", "Thriller"],
    tag: ["viaggi nel tempo", "paradosso", "germania", "cupo"],
    anno: 2017,
    durataMinuti: 58,
    piattaforma: "Netflix",
    regista: "Baran bo Odar",
    cast: ["Louis Hofmann", "Lisa Vicari"],
    descrizione: "La scomparsa di un bambino svela un intreccio temporale tra quattro famiglie.",
    posterUrl: "https://placehold.co/300x450?text=Dark",
    votoMedio: 8.7,
  },
  {
    titolo: "The Office",
    tipo: "serie",
    generi: ["Commedia"],
    tag: ["mockumentary", "ufficio", "quotidiano", "leggero"],
    anno: 2005,
    durataMinuti: 22,
    piattaforma: "Prime Video",
    regista: "Greg Daniels",
    cast: ["Steve Carell", "John Krasinski", "Rainn Wilson"],
    descrizione: "La vita quotidiana degli impiegati di una cartiera, in stile documentario.",
    posterUrl: "https://placehold.co/300x450?text=The+Office",
    votoMedio: 9.0,
  },
  {
    titolo: "Chernobyl",
    tipo: "serie",
    generi: ["Dramma", "Biografico", "Thriller"],
    tag: ["disastro", "storia vera", "urss", "cupo"],
    anno: 2019,
    durataMinuti: 65,
    piattaforma: "Prime Video",
    regista: "Johan Renck",
    cast: ["Jared Harris", "Stellan Skarsgård"],
    descrizione: "La ricostruzione del disastro nucleare del 1986 e delle sue conseguenze.",
    posterUrl: "https://placehold.co/300x450?text=Chernobyl",
    votoMedio: 9.3,
  },
];
